/** REVIEWS **/
export const INVALIDATE_REVIEWS = 'INVALIDATE_REVIEWS'
export const REVIEWS_REQUEST = 'REVIEWS_REQUEST'
export const REVIEWS_SUCCESS = 'REVIEWS_SUCCESS'
export const REVIEWS_ERROR = 'REVIEWS_ERROR'

/** REVIEW FORM **/
export const CHANGE_REVIEW_ACTION = 'CHANGE_REVIEW_ACTION'
export const SUBMIT_REVIEW = 'SUBMIT_REVIEW'
export const REVIEW_FORM_SUCCESS = 'REVIEW_FORM_SUCCESS'
export const REVIEW_FORM_ERROR = 'REVIEW_FORM_ERROR'
export const COFFEESHOPS_REQUEST = 'COFFEESHOPS_REQUEST'
export const COFFEESHOPS_SUCCESS = 'COFFEESHOPS_SUCCESS'
export const COFFEESHOPS_ERROR = 'COFFEESHOPS_ERROR'

/** AUTH AND CREDENTIALS **/
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const AUTH_ERROR = 'AUTH_ERROR'
