/** MODEL METHODS **/
export const LB_REQUEST = 'LB_REQUEST'
export const LB_SUCCESS = 'LB_SUCCESS'
export const LB_RECEIVE = 'LB_RECEIVE'
export const LB_ERROR = 'LB_ERROR'

/** AUTH AND CREDENTIALS **/
export const LB_LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LB_LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LB_LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LB_LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const LB_REGISTER_REQUEST = 'REGISTER_REQUEST'
export const LB_REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const LB_AUTH_ERROR = 'AUTH_ERROR'